// Map layer names to a descriptive string to show in the infobox
const friendlyNames: { [key: string]: string } = {
  power_transformer: 'Transformateur',
  power_tower: 'Pylône',
  power_pole: 'Poteau',
  power_generator: 'Générateur',
  power_wind_turbine: 'Eolienne',
  power_substation: 'Poste',
  power_substation_point: 'Poste',
  power_switch: 'Organe',
  power_compensator: 'Compensateur',
  power_cable: 'Câble électrique',
  power_line: 'Ligne électrique',
  power_line_underground: 'Câble électrique',
  power_line_case: 'Câble électrique',
  power_line_label: 'Ligne électrique',
  power_solar_panel: 'Panneau solaire',
  power_plant: 'Centrale électrique',
  telecoms_communication_line: 'Telecoms line',
  telecoms_mast: 'Pylône télécom',
  telecoms_data_center: 'Datacenter',
  petroleum_pipeline: 'Canalisation',
  petroleum_pipeline_case: 'Canalisation',
  petroleum_pipeline_label: 'Canalisation',
  petroleum_well: 'Puits',
  water_pipeline: 'Canalisation',
  water_channel: 'Flux',
  water_channel_arrow: 'Flux',
  water_flow_inlet: 'Embouchure',
  water_flow_outlet: 'Exutoire',
  water_body: 'Retenue',
  water_structure_gear: 'Hydraulique',
  waternatural_river: 'Cours d\'eau',
  waternatural_falls: 'Cascade',
  waternatural_fords: 'Gué',
  water_obstacle_line: 'Obstacle',
  water_obstacle_poly: 'Obstacle',
  operator: 'Exploitant'
}

export default friendlyNames
